// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TeaShop.Data;

#nullable disable

namespace TeaShop.Data.Migrations
{
    [DbContext(typeof(TeashopContext))]
    [Migration("20260408171633_AddImagenUrlToProducto")]
    partial class AddImagenUrlToProducto
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TeaShop.Models.ItemPedido", b =>
                {
                    b.Property<int>("ItemPedidoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemPedidoId"));

                    b.Property<double>("Cantidad")
                        .HasColumnType("float");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.HasKey("ItemPedidoId");

                    b.HasIndex("PedidoId");

                    b.HasIndex("ProductoId");

                    b.ToTable("ItemsPedido");
                });

            modelBuilder.Entity("TeaShop.Models.Pedido", b =>
                {
                    b.Property<int>("PedidoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PedidoId"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PrecioTotal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("PedidoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("TeaShop.Models.Producto", b =>
                {
                    b.Property<int>("ProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductoId"));

                    b.Property<bool>("EsOrganico")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCaducidad")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("TipoProducto")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.HasKey("ProductoId");

                    b.ToTable("Productos");

                    b.HasDiscriminator<string>("TipoProducto").HasValue("Producto");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("TeaShop.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EsSocio")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("TeaShop.Models.Comida", b =>
                {
                    b.HasBaseType("TeaShop.Models.Producto");

                    b.Property<bool>("Gluten")
                        .HasColumnType("bit");

                    b.Property<string>("TipoComida")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Comida");

                    b.HasData(
                        new
                        {
                            ProductoId = 5,
                            EsOrganico = false,
                            FechaCaducidad = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Tarta de Pistacho",
                            Origen = "España",
                            Precio = 25.0m,
                            Stock = 5000,
                            Gluten = true,
                            TipoComida = "Dulce"
                        },
                        new
                        {
                            ProductoId = 6,
                            EsOrganico = true,
                            FechaCaducidad = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Cookie de Avena",
                            Origen = "España",
                            Precio = 17.8m,
                            Stock = 2500,
                            Gluten = false,
                            TipoComida = "Dulce"
                        },
                        new
                        {
                            ProductoId = 7,
                            EsOrganico = false,
                            FechaCaducidad = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Sándwich Vegetal",
                            Origen = "Francia",
                            Precio = 23.5m,
                            Stock = 2200,
                            Gluten = true,
                            TipoComida = "Salado"
                        },
                        new
                        {
                            ProductoId = 8,
                            EsOrganico = true,
                            FechaCaducidad = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Wrap de Pollo",
                            Origen = "Reino Unido",
                            Precio = 20.2m,
                            Stock = 6400,
                            Gluten = false,
                            TipoComida = "Salado"
                        });
                });

            modelBuilder.Entity("TeaShop.Models.Te", b =>
                {
                    b.HasBaseType("TeaShop.Models.Producto");

                    b.Property<string>("TipoHoja")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Te");

                    b.HasData(
                        new
                        {
                            ProductoId = 1,
                            EsOrganico = true,
                            FechaCaducidad = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Té Matcha",
                            Origen = "Japón",
                            Precio = 50.5m,
                            Stock = 1000,
                            TipoHoja = "Verde"
                        },
                        new
                        {
                            ProductoId = 2,
                            EsOrganico = false,
                            FechaCaducidad = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Té Chai",
                            Origen = "India",
                            Precio = 32.0m,
                            Stock = 10000,
                            TipoHoja = "Negro"
                        },
                        new
                        {
                            ProductoId = 3,
                            EsOrganico = false,
                            FechaCaducidad = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Té Puerh",
                            Origen = "China",
                            Precio = 22.0m,
                            Stock = 10000,
                            TipoHoja = "Rojo"
                        },
                        new
                        {
                            ProductoId = 4,
                            EsOrganico = true,
                            FechaCaducidad = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Té Oolong",
                            Origen = "China",
                            Precio = 45.0m,
                            Stock = 1500,
                            TipoHoja = "Azul"
                        });
                });

            modelBuilder.Entity("TeaShop.Models.ItemPedido", b =>
                {
                    b.HasOne("TeaShop.Models.Pedido", "Pedido")
                        .WithMany("Items")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeaShop.Models.Producto", "Producto")
                        .WithMany("ItemPedido")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("TeaShop.Models.Pedido", b =>
                {
                    b.HasOne("TeaShop.Models.Usuario", "Usuario")
                        .WithMany("Pedidos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TeaShop.Models.Pedido", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("TeaShop.Models.Producto", b =>
                {
                    b.Navigation("ItemPedido");
                });

            modelBuilder.Entity("TeaShop.Models.Usuario", b =>
                {
                    b.Navigation("Pedidos");
                });
#pragma warning restore 612, 618
        }
    }
}
